name: Auto Sign-In

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  push:
    branches:
      - main
  workflow_dispatch:  # 添加手动触发功能

jobs:
  sign-in:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Download ChromeDriver
      run: |
        Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/$(Invoke-RestMethod -Uri https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_win32.zip -OutFile chromedriver.zip
        Expand-Archive chromedriver.zip -DestinationPath $env:USERPROFILE

    - name: Run sign-in script
      env:
        PATH: $env:USERPROFILE\chromedriver_win32;$env:PATH
      run: python mua.py
