name: Auto Sign-In

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  push:
    branches:
      - main
  workflow_dispatch:  # 添加手动触发功能

jobs:
  sign-in:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install undetected-chromedriver selenium

    - name: Run sign-in script
      run: python mua.py